# Generated by Django 4.2.3 on 2023-07-20 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиента', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'Рассылку', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
